# Generated by Django 3.1 on 2021-01-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210105_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='lastname',
        ),
    ]
