# Generated by Django 3.1 on 2021-01-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210107_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_type',
            field=models.CharField(choices=[('LS', 'Lesson'), ('EX', 'Exercise')], default='LS', max_length=2),
            preserve_default=False,
        ),
    ]
