# Generated by Django 3.1 on 2021-01-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_tutorial_tutorial_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseprogress',
            old_name='progress',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='lessonprogress',
            old_name='progress',
            new_name='completed',
        ),
    ]
