# Generated by Django 3.1 on 2021-01-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210108_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.assignment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.assignment')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.assignment')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.exercise')),
            ],
        ),
    ]
