# Generated by Django 3.1.4 on 2021-01-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_exercisesubmissionevent_lessonsubmissionevent_loginevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmissionevent',
            name='frequency',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonsubmissionevent',
            name='frequency',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
